name: Deploy Blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:        
    runs-on: ubuntu-latest 
    steps:                 
      - name: Checkout     
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile --registry=https://registry.npmmirror.com

      - name: Build Hexo
        run: pnpm exec hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HEXO_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: gh-pages